# Generated by Django 4.2 on 2025-11-10 20:33

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(db_column='RoleID', primary_key=True, serialize=False)),
                ('role_name', models.CharField(db_column='RoleName', max_length=255)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user_setting_id', models.AutoField(db_column='UserSettingID', primary_key=True, serialize=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], db_column='Theme', default='light', max_length=10)),
                ('date_format', models.CharField(blank=True, db_column='DateFormat', max_length=20, null=True)),
                ('page_size', models.IntegerField(db_column='PageSize', default=10)),
                ('saved_filters', models.JSONField(db_column='SavedFilters', default=dict)),
                ('user', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserSettings',
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('session_log_id', models.AutoField(db_column='SessionLogID', primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(db_column='LoginTime', null=True)),
                ('logout_time', models.DateTimeField(db_column='LogoutTime', null=True)),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SessionLog',
            },
        ),
        migrations.CreateModel(
            name='Backups',
            fields=[
                ('backup_id', models.AutoField(db_column='BackupID', primary_key=True, serialize=False)),
                ('created_at', models.CharField(db_column='CreatedAt', max_length=255, null=True)),
                ('type', models.CharField(db_column='Type', max_length=255, null=True)),
                ('file_path', models.TextField(db_column='FilePath', null=True)),
                ('status', models.CharField(db_column='Status', max_length=100, null=True)),
                ('user', models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Backups',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_log_id', models.AutoField(db_column='AuditLogID', primary_key=True, serialize=False)),
                ('table_name', models.CharField(db_column='TableName', max_length=255, null=True)),
                ('operation', models.CharField(db_column='Operation', max_length=255, null=True)),
                ('datetime', models.DateTimeField(db_column='Datetime', null=True)),
                ('old_value', models.CharField(db_column='OldValue', max_length=255, null=True)),
                ('new_value', models.CharField(db_column='NewValue', max_length=255, null=True)),
                ('field', models.CharField(db_column='Field', max_length=255, null=True)),
                ('user', models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AuditLog',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(db_column='UserRoleID', primary_key=True, serialize=False)),
                ('role', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserRole',
                'unique_together': {('role', 'user')},
            },
        ),
    ]
