# Generated by Django 4.2 on 2025-11-10 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_variants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('order_item_id', models.AutoField(db_column='OrderItemID', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(db_column='Quantity', default=1)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('product_variant', models.ForeignKey(db_column='ProductVariantID', on_delete=django.db.models.deletion.CASCADE, to='product_variants.productvariant')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CartItems',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(db_column='CartID', primary_key=True, serialize=False)),
                ('items', models.ManyToManyField(blank=True, related_name='carts', to='cart.cartitem')),
                ('user', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
    ]
