# Generated by Django 4.2 on 2025-11-10 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('gemstone_id', models.AutoField(db_column='GemstoneID', primary_key=True, serialize=False)),
                ('name_color', models.CharField(db_column='NameColor', max_length=255)),
                ('color_code', models.CharField(blank=True, db_column='ColorCode', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'db_table': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('size_id', models.AutoField(db_column='SizeID', primary_key=True, serialize=False)),
                ('size', models.CharField(db_column='Size', max_length=100)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'db_table': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('product_variant_id', models.AutoField(db_column='ProductVariantID', primary_key=True, serialize=False)),
                ('structure', models.CharField(blank=True, db_column='Structure', max_length=100, null=True)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('photo', models.TextField(blank=True, db_column='Photo', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('quantity', models.IntegerField(db_column='Quantity', null=True)),
                ('color', models.ForeignKey(db_column='ColorID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='product_variants.colors')),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
                ('size', models.ForeignKey(db_column='SizeID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='product_variants.sizes')),
                ('store', models.ForeignKey(db_column='StoreID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variants', to='stores.store')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'db_table': 'ProductVariant',
            },
        ),
    ]
