# Generated by Django 4.2 on 2025-11-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_variants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='previous_price',
            field=models.DecimalField(blank=True, db_column='PreviousPrice', decimal_places=2, max_digits=10, null=True),
        ),
    ]
