# Generated by Django 4.2 on 2025-11-12 17:57

from django.db import migrations, models
import django.db.models.deletion


def forward_copy_variant_photos(apps, schema_editor):
    Variant = apps.get_model('product_variants', 'ProductVariant')
    VariantImage = apps.get_model('product_variants', 'ProductVariantImage')
    to_create = []
    for variant in Variant.objects.exclude(photo__isnull=True).exclude(photo__exact=''):
        to_create.append(VariantImage(
            variant=variant,
            source_url=variant.photo,
            alt=str(variant),
            order=0,
            is_primary=True,
        ))
    if to_create:
        VariantImage.objects.bulk_create(to_create, ignore_conflicts=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('product_variants', '0002_productvariant_previous_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_variants/%Y/%m/%d/')),
                ('source_url', models.URLField(blank=True)),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_variants.productvariant')),
            ],
            options={
                'verbose_name': 'Variant Image',
                'verbose_name_plural': 'Variant Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(forward_copy_variant_photos, noop),
        migrations.RemoveField(
            model_name='productvariant',
            name='photo',
        ),
    ]
