# Generated by Django 4.2 on 2025-11-11 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.AutoField(db_column='ImageID', primary_key=True, serialize=False)),
                ('image_url', models.TextField(db_column='ImageURL')),
                ('alt_text', models.CharField(blank=True, db_column='AltText', max_length=255)),
                ('position', models.PositiveIntegerField(db_column='Position', default=0)),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'db_table': 'ProductImages',
                'ordering': ['position', 'image_id'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.AutoField(db_column='FavoriteID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='catalog.product')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Favorites',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
