# Generated by Django 4.2 on 2025-11-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_productreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
