# Generated by Django 4.2 on 2025-11-11 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderShareToken",
            fields=[
                ("token_id", models.AutoField(primary_key=True, serialize=False)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("channel", models.CharField(blank=True, max_length=50, null=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_tokens",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "OrderShareToken",
            },
        ),
        migrations.AddIndex(
            model_name="ordersharetoken",
            index=models.Index(
                fields=["token", "expires_at"], name="OrderShareT_token_5be00b_idx"
            ),
        ),
    ]
