# Generated by Django 4.2 on 2025-11-10 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(db_column='AddressID', primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, db_column='City', max_length=255, null=True)),
                ('street', models.CharField(blank=True, db_column='Street', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(db_column='StoreID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('business_hours', models.CharField(blank=True, db_column='BusinessHours', max_length=255, null=True)),
                ('photo', models.TextField(blank=True, db_column='Photo', null=True)),
                ('address', models.ForeignKey(blank=True, db_column='AddressID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.address')),
            ],
            options={
                'db_table': 'Stores',
            },
        ),
    ]
