# Generated by Django 4.2 on 2025-11-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="AuditLogs_event_t_eccb46_idx",
            old_name="audit_event_created_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="AuditLogs_app_lab_3e64b0_idx",
            old_name="audit_model_idx",
        ),
    ]
